name:                gameboy-emulator
version:             0.1.0.0
# github:
license:             GPL-3
# author:
# maintainer:
# copyright:

extra-source-files:
- README.md

description:         An emulator for the Nintendo Game Boy

dependencies:
- base >= 4.7 && < 5
- containers
- bytestring
- mtl
- lens
- finite-typelits
- indexed-list-literals
- transformers
- text
- SDL
- vector
- array
- time
- random

default-extensions:
- TemplateHaskell
- FlexibleContexts
- GeneralizedNewtypeDeriving
- GADTs
- TypeOperators
- KindSignatures
- DataKinds
- TypeFamilies
- InstanceSigs
- RankNTypes
- ConstraintKinds
- ScopedTypeVariables
- TypeApplications
- LambdaCase
- ViewPatterns
- MultiParamTypeClasses
- FlexibleInstances
- TupleSections
- StandaloneDeriving
- PolyKinds
- TypeFamilyDependencies
- OverloadedStrings
- RecordWildCards
- Strict
- StrictData

library:
  source-dirs: src
  ghc-options:
  - -O2

executables:
  gb-emulator:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -O2
    - -rtsopts
    dependencies:
    - gameboy-emulator

tests:
  gameboy-emulator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gameboy-emulator
